### ISSUE TITLE
Template error: instance of Fn::GetAtt references undefined resource C9InstanceProfile

### ISSUE THREAD

**Issue by bwboy** [aws-quickstart/quickstart-cloud9-ide#20]
I use the online version which link is 

https://console.aws.amazon.com/cloudformation/home?region=us-west-2#/stacks/new?stackName=AWS-Cloud9-IDE&templateURL=https://aws-quickstart.s3.amazonaws.com/quickstart-cloud9-ide/templates/cloud9-ide-master.template.yaml

When I run the scripts,the cloud formation the error message is below:

---
Template error: instance of Fn::GetAtt references undefined resource C9InstanceProfile
---

**Comment by bwboy** [comment]
@jayyeras  is there any suggestion?

**Comment by bwboy** [comment]
@jayyeras Thanks a lot~ I will be waiting for the release.

**Comment by jayyeras** [comment]
@bwboy Sorry for the delay. This issue has now been resolved. Thank you for your patience!

**Comment by bwboy** [comment]
@jayyeras Thanks a lot.
