### ISSUE TITLE
Migrate CopyZips to submodule pattern

### ISSUE THREAD

**Issue by andrew-glenn** [aws-quickstart/quickstart-cloud9-ide#21]
Python 2.7 is EOL in January 2020. We need to upgrade the CopyZips function prior to then.

**Comment by rhboyd** [comment]
it looks like it's 3.6?

https://github.com/aws-quickstart/quickstart-cloud9-ide/blob/develop/templates/cloud9-ide-instance.yaml#L191

**Comment by andrew-glenn** [comment]
@rhboyd  - Indeed. This was opened via automation; However, I wish to leave it open for now so we can track migrating our CopyZips lambda to a submodule pattern for ease of maintenance.
